version: '3.9'

services:
  backend:
    build: ./quizapp            # Path to your Django Dockerfile
    container_name: quizapp
    ports:
      - "8000:8000"             # Host:Container port mapping
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
    volumes:
      - ./quizapp/db:/quizapp/db  # Bind mount for SQLite persistence
      - /home/ubuntu/quizapp/db:/quizapp/db
      # - ./quizapp:/quizapp        # Optional: sync code for live edits
    # environment:
    #   - DEBUG=1                  # Optional: pass env vars
    stdin_open: true
    tty: true
  frontend:
    build: ./frontend            # Path to your React Dockerfile
    container_name: myquizappfrontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules           # Sync code for live edits
    command: ["npm", "run", "dev"]