# Generated by Django 5.1.6 on 2025-07-31 17:10

import myapp.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', myapp.managers.CustomUserManager()),
            ],
        ),
    ]
